name: xwiki # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '13.10.8' # just for humans, typically '1.2+git' or '1.3.2'
summary:  XWiki 
description: XWiki is a free wiki software platform written in Java with a design emphasis
 on extensibility.
 .
 XWiki is an easily installed wiki and collaboration platform with features such as
 WYSIWYG editing, OpenOffice based document import/export, semantic annotations
 and tagging, and advanced permissions management.
 .
 XWiki is designed to help teams collaborate more efficiently. It
  runs in a Java servlet container such as Tomcat.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode
hooks:
       install:
          plugs: [network,home]
parts:
  xwiki:
    plugin: dump
    source: https://nexus.xwiki.org/nexus/content/groups/public/org/xwiki/platform/xwiki-platform-distribution-jetty-hsqldb/13.10.8/xwiki-platform-distribution-jetty-hsqldb-13.10.8.zip
    source-type: zip
    
    override-build: |
      snapcraftctl build
      mv xwiki-platform-distribution-jetty-hsqldb-13.10.8/* .
      rm -r xwiki-platform-distribution-jetty-hsqldb-13.10.8
      chmod u+x start_xwiki.sh
      chmod u+x stop_xwiki.sh
    
