name: xwiki # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '13.10.8' # just for humans, typically '1.2+git' or '1.3.2'
summary:  XWiki 
description: XWiki is a free wiki software platform written in Java with a design emphasis
 on extensibility.
 .
 XWiki is an easily installed wiki and collaboration platform with features such as
 WYSIWYG editing, OpenOffice based document import/export, semantic annotations
 and tagging, and advanced permissions management.
 .
 XWiki is designed to help teams collaborate more efficiently. It
  runs in a Java servlet container such as Tomcat.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict
hooks:
       install:
          plugs: [home]
parts:
  xwiki:
    plugin: dump
    source: https://nexus.xwiki.org/nexus/content/groups/public/org/xwiki/platform/xwiki-platform-distribution-jetty-hsqldb/13.10.8/xwiki-platform-distribution-jetty-hsqldb-13.10.8.zip
    source-type: zip    
    override-build: |
      snapcraftctl build
      mv xwiki-platform-distribution-jetty-hsqldb-13.10.8/* . 
      rm -r xwiki-platform-distribution-jetty-hsqldb-13.10.8  
      mv $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-* $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk
      rm $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk/lib/security/cacerts
      rm $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk/lib/security/blacklisted.certs
      cp /etc/ssl/certs/java/cacerts $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk/lib/security/cacerts
      cp /etc/ssl/certs/java/cacerts $SNAPCRAFT_PART_INSTALL/etc/ssl/certs/java/cacerts

    build-packages:
    - ca-certificates
    - ca-certificates-java
    - openjdk-11-jre-headless
    stage-packages:
    - openjdk-11-jre-headless
    - openjdk-11-jdk 
    - diffutils

  scripts:
    source: ./scripts/
    plugin: dump
    override-build: |
      chmod +x start.sh
      chmod +x stop.sh     
      chmod +x copy.sh
      sudo chmod +x update.sh
      snapcraftctl build 
    override-prime: | 
      snapcraftctl prime
      mv mysql-connector-java-8.0.29.jar xwiki-platform-distribution-jetty-hsqldb-13.10.8/webapps/xwiki/WEB-INF/lib/ 
      mv mariadb-java-client-3.0.6.jar xwiki-platform-distribution-jetty-hsqldb-13.10.8/webapps/xwiki/WEB-INF/lib/
      mv postgresql-42.4.0.jar xwiki-platform-distribution-jetty-hsqldb-13.10.8/webapps/xwiki/WEB-INF/lib/
      mv ojdbc8.jar xwiki-platform-distribution-jetty-hsqldb-13.10.8/webapps/xwiki/WEB-INF/lib/
      mv db2jcc-db2jcc4.jar xwiki-platform-distribution-jetty-hsqldb-13.10.8/webapps/xwiki/WEB-INF/lib/
      mv derby.jar xwiki-platform-distribution-jetty-hsqldb-13.10.8/webapps/xwiki/WEB-INF/lib/
      mv jtds-1.3.1.jar xwiki-platform-distribution-jetty-hsqldb-13.10.8/webapps/xwiki/WEB-INF/lib/
      mv h2-2.1.214.jar xwiki-platform-distribution-jetty-hsqldb-13.10.8/webapps/xwiki/WEB-INF/lib/ 
      
    after: [xwiki]

apps:
  start:
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk/
      PATH: $JAVA_HOME/bin:$PATH
    command: ./start.sh
    plugs: [home,network,network-bind]
  stop:
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk/
      PATH: $JAVA_HOME/bin:$PATH
    command: ./stop.sh
    plugs: [home,network,network-bind] 
  save:
    command: ./copy.sh
    plugs: [home]  
  update:
    command: ./update.sh
    plugs: [home]    
   
