name: xwiki # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '14.4.1' # just for humans, typically '1.2+git' or '1.3.2'
summary:  XWiki 
description: XWiki offers a generic platform for developing projects and collaborative applications using the wiki paradigm. Platform XWiki Platform is the generic wiki platform offering runtime services for applications built on top of it.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots
hooks:
  configure:
    plugs: [home]
parts:
  xwiki:
    source: https://nexus.xwiki.org/nexus/content/groups/public/org/xwiki/platform/xwiki-platform-distribution-war/13.10.7/xwiki-platform-distribution-war-13.10.7.war
    source-type: zip
    plugin: dump
    organize:
      META-INF: xwiki/META-INF
      WEB-INF: xwiki/WEB-INF
      redirect: xwiki/redirect
      skins: xwiki/skins
      templates: xwiki/templates
      resources: xwiki/resources
      xwiki: webapps/xwiki       
    build-packages:
      - wget
      - unzip
      - ca-certificates
      - ca-certificates-java
      - openjdk-11-jre-headless
    stage-packages:
      - openjdk-11-jdk  
    after: [tomcat]
  tomcat:
    plugin: ant
    source: https://svn.apache.org/repos/asf/tomcat/archive/tc9.0.x/trunk/
    source-type: svn
    prime:
      - -webapps/docs
      - -webapps/examples
      - -webapps/manager
      - -webapps/host-manager
      - -webapps/ROOT
    override-build: |
      # echo "install java 10 from ppa"
      # add-apt-repository ppa:linuxuprising/java
      # apt-get update --yes
      # apt-get install --yes oracle-java10-installer
      # apt-get install --yes oracle-java10-set-default
      echo "Pre build steps"
      cp build.properties.default build.properties
      snapcraftctl build
      echo "Post build steps"
      cp -r output/build/* $SNAPCRAFT_PART_INSTALL
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/tomcat-launch
      #!/bin/sh
      export JRE_HOME=\${SNAP}/usr/lib/jvm/java-11-openjdk-amd64
      export JAVA_HOME=\${SNAP}/usr/lib/jvm/java-11-openjdk-amd64
      export CATALINA_HOME=\${SNAP}
      export CATALINA_BASE=\${SNAP_DATA}
      export CATALINA_TMPDIR=/tmp
      cp -rn \${CATALINA_HOME}/conf \${CATALINA_BASE}/
      # this creates a second copy of the webapps directory.
      # No problem but need to see if we can clean up.
      # seems like an organize statement might do the trick.
      cp -rn \${CATALINA_HOME}/webapps \${CATALINA_BASE}/
      exec \${CATALINA_HOME}/bin/catalina.sh run
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/tomcat-launch 
      
    stage-packages:
      - libc6
      - libbz2-1.0
      - libgcc1
      - libcomerr2
      - libgcrypt20
      - liblzma5
      - libmount1
      - libncursesw5
      - libselinux1
      - libtinfo5
      - libuuid1
      - libstdc++6
      - libsmartcols1
      - libgpg-error0
      - libblkid1
      - zlib1g
      - libpcre3
      - libsystemd0
  scripts:
    source: ./scripts/
    source-type: local
    plugin: dump
    organize:
      setenv.sh: bin/setenv.sh    
    after: [xwiki]

      
apps:
  tomcat:
    command: tomcat-launch
    daemon: simple
    plugs: [network, network-bind]
    


